In [120]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import scipy.optimize as opt
from sklearn.model_selection import train_test_split

In [121]:
data = pd.read_excel("C:/Users/Niku/Documents/dataset/datatest.xlsx")
data.shape

(1992, 36)

In [122]:
Normdata = data
Normdata = np.matrix(Normdata)
for i in range(0, Normdata.shape[1]):
    cur = Normdata[:, i]
    mx = max(cur)*1.0
    mn = min(cur)*1.0
    for j in range(0, len(cur)):
        cur[j] = (cur[j] - mn)/(mx - mn)
    Normdata[:, i] = cur
colus = Normdata.shape[1]
X = Normdata[:,0:colus-1]
y = Normdata[:,colus-1:colus]
# convert to numpy arrays and initalize the parameter array theta
#X = np.array(X.values)
#y = np.array(y.values)

In [123]:
X = np.matrix(data)
X = X[:,0:3]

In [124]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state=1)
X_train.shape, y_train.shape

((996L, 3L), (996L, 1L))

In [125]:
X.shape

(1992L, 3L)

In [126]:
k = 2
rows = X.shape[0]
cols = X.shape[1]
cent = np.zeros((k, X.shape[1]))

In [127]:
def closest_centroid(X, cent, k):
    min_dist = 100000000
    closest = 0
    for i in range(k):
        dist = X - cent[i]
        dist = np.array(dist)
        dist = np.sum(dist**2)
        if dist < min_dist:
            min_dist = dist
            closest = i
    return closest

In [128]:
def kmeans():
    cent = np.zeros((k, X.shape[1]))
    c = np.zeros(rows)
    for i in range(k):
        r = int(np.random.rand()*rows)
        cent[i] = X[r]
    print cent
    for iter in range(100):
        for i in range(rows):
            c[i] = closest_centroid(X[i, :], cent, k)
            #print c[i]
        cluster0 = X[np.where(c == 0)[0],:]
        cluster1 = X[np.where(c == 1)[0],:]
        for j in range(cols):
            cent[0, j] = np.mean(cluster0[:,j])
        for j in range(cols):
            cent[1, j] = np.mean(cluster1[:,j])
    return c, cent, cluster0, cluster1

In [129]:
y_pred, cent, clus0, clus1 = kmeans()

[[  2.49  15.98  74.78]
 [  2.87   0.78  96.6 ]]


In [130]:
y_pred = 1 - y_pred
y_pred

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [131]:
correct = [1 if a == b else 0 for (a, b) in zip(y_pred, y)]
accuracy = (sum(map(int, correct)) / float(len(correct)))
print 'accuracy = {0}%'.format(accuracy * 100)

accuracy = 84.6385542169%


In [132]:
y_pred

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])