In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from collections import Counter, defaultdict
import pylab as pl
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix

In [2]:
data = pd.read_excel("C:\Users\Niku\Documents\dataset\dataset_40_attributes5.xlsx")
data2 = pd.read_excel("C:\Users\Niku\Documents\dataset\X_dataset.xlsx")
print data.shape
X = data2
y = pd.read_excel("C:\Users\Niku\Documents\dataset\y_category.xlsx")
X = np.matrix(X)
y = np.matrix(y)
print X.shape 
print y.shape

(1992, 57)
(1992L, 35L)
(1992L, 1L)


In [3]:
cat = np.zeros(X.shape[0])
cat.shape

(1992L,)

In [4]:
for i in range(0, X.shape[0]):
    if(y[i] > 0.2):
        cat[i] = 1
    else:
        cat[i] = 0

In [5]:
np.savetxt('fname.txt', cat) 

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state=1)
print X_train.shape
print X_test.shape
print y_test.shape
print type(y_train)

(996L, 35L)
(996L, 35L)
(996L, 1L)
<class 'numpy.matrixlib.defmatrix.matrix'>


In [7]:
def g(z):
    temp = 1 + np.exp(-z)
    temp2 = 1/temp
    return temp2

In [8]:
def gradient(theta, X, y, alpha):
    X = np.matrix(X)
    y = np.matrix(y)
    theta = np.matrix(theta)
    hofx = g(X*theta.T)
    err = hofx - y
    term1 = ((X.T * err) / len(X)).T 
    term2 = ((alpha / len(X)) * theta)
    grad = term1 + term2
    zero_intercept = np.multiply(err, X[:,0])
    grad[0, 0] = np.sum(zero_intercept)
    return np.array(grad).ravel()

In [9]:
def costFunction(theta, X, y, alpha):
    theta = np.matrix(theta)
    #hofx = g(X*theta.T)
    #term1 = np.multiply(y, np.log(hofx))
    #term2 = np.multiply((1-y), np.log(1-hofx))
    #par_to_regul = theta[:,1:theta.shape[1]]
    #sqr_term = np.power(par_to_regul, 2)
    #regul_term = alpha*len(X)*np.sum(sqr_term)
    #cost = np.sum(((-term1)+(-term2))/len(X)) + regul_term
    first = np.multiply(-y, np.log(g(X * theta.T)))
    second = np.multiply((1 - y), np.log(1 - g(X * theta.T)))
    reg = (alpha / 2 * len(X)) * np.sum(np.power(theta[:,1:theta.shape[1]], 2))
    return np.sum(first - second) / (len(X)) + reg
    #return cost

In [10]:
rows = X.shape[0]
params = X.shape[1]
y = np.matrix(y)
all_theta = np.zeros((31, params + 1))

X = np.insert(X, 0, values=np.ones(rows), axis=1)

theta = np.zeros(params + 1)

y_0 = np.array([1 if label == 0 else 0 for label in y])
y_0 = np.reshape(y_0, (rows, 1))

X.shape, y_0.shape, theta.shape, all_theta.shape

((1992L, 36L), (1992L, 1L), (36L,), (31L, 36L))

In [12]:
from scipy.optimize import minimize
learning_rate = 0.1
fmin = minimize(fun=costFunction, x0=theta, args=(X, y, learning_rate), method='TNC', jac=gradient)
theta = fmin.x

In [13]:
theta

array([  9.35885500e-04,   2.90239290e-04,  -5.68512236e-03,
        -1.80484167e-03,   6.62613048e-03,   1.51299818e-02,
         6.18177835e-04,   1.36018232e-03,  -1.91996427e-04,
        -1.81161844e-04,   2.42452403e-02,  -1.44937564e-04,
         2.12916419e-03,   1.69794261e-03,   1.02847441e-02,
         1.70347909e-03,   1.56246732e-04,   5.15231289e-03,
         4.00187523e-03,   9.86471637e-03,  -7.53952052e-03,
         3.03589732e-03,   1.14821717e-03,   5.74286591e-03,
        -1.63072520e-05,   1.75459231e-03,  -2.10573977e-03,
         5.25442210e-03,   6.84026058e-03,   1.05980820e-03,
         2.01191594e-03,   1.77063865e-03,  -1.71024965e-03,
         2.83673511e-03,  -2.75204697e-04,   2.25104478e-04])

In [14]:
def predict_all(X, theta):
    rows = X.shape[0]
    params = X.shape[1]
    num_labels = theta.shape[0]
    
    # same as before, insert ones to match the shape
    X = np.insert(X, 0, values=np.ones(rows), axis=1)
    
    # convert to matrices
    X = np.matrix(X)
    theta = np.matrix(theta)
    p = X * theta.T
    # compute the class probability for each class on each training instance
    h = g(X * theta.T)
    print h
    # create array of the index with the maximum probability
    #h_argmax = np.argmax(h, axis=1)
    # because our array was zero-indexed we need to add one for the true label prediction
    #h_argmax = h_argmax + 1
    #print h_argmax
    return h

In [15]:
y_pred = predict_all(X_test, theta)

[[  8.23283848e-01]
 [  1.55959031e-01]
 [  7.79247456e-01]
 [  4.28750277e-01]
 [  9.31932461e-01]
 [  6.64822085e-01]
 [  2.17614692e-01]
 [  6.94453383e-01]
 [  6.21173257e-01]
 [  4.96075187e-01]
 [  3.45360448e-01]
 [  5.30876646e-01]
 [  4.21254883e-01]
 [  4.72117015e-01]
 [  6.79309386e-01]
 [  4.55455016e-01]
 [  4.06247249e-01]
 [  4.02014711e-01]
 [  9.35316695e-01]
 [  3.30626284e-01]
 [  6.51426224e-01]
 [  2.83332393e-01]
 [  2.45267792e-01]
 [  4.68563020e-01]
 [  2.58362824e-01]
 [  4.50872163e-01]
 [  5.17966268e-01]
 [  6.63249239e-01]
 [  6.39838134e-01]
 [  8.15750921e-01]
 [  7.36412438e-01]
 [  8.24462709e-01]
 [  2.00101268e-01]
 [  8.07926101e-01]
 [  4.28716590e-01]
 [  2.98475932e-01]
 [  4.12814351e-01]
 [  4.08247047e-01]
 [  5.95759793e-02]
 [  5.04651908e-01]
 [  4.85355914e-01]
 [  3.24494939e-01]
 [  7.25588941e-01]
 [  1.37817786e-01]
 [  4.50620094e-01]
 [  9.49758598e-01]
 [  4.42482781e-01]
 [  1.37002718e-01]
 [  5.54621714e-01]
 [  6.81821402e-01]


In [16]:
for i in range(0, len(y_pred)):
    if y_pred[i] < 0.2 :
        y_pred[i] = 0
    else:
        y_pred[i] = 1

In [17]:
y_pred

matrix([[ 1.],
        [ 0.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 0.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 0.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 0.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 

In [18]:
correct = [1 if a == b else 0 for (a, b) in zip(y_pred, y_test)]
accuracy = (sum(map(int, correct)) / float(len(correct)))
print 'accuracy = {0}%'.format(accuracy * 100)

accuracy = 27.8112449799%


In [21]:
type(y_pred)

numpy.matrixlib.defmatrix.matrix